### ISSUE TITLE
Gráfico da simulação meta competition

### ISSUE THREAD

**Issue by RPGraciotti** [ecovirt/EcoVirtualPlugin#10]
Quando rodo o modelo de coexistência das duas metapopulações, enquanto o gráfico da simulação roda, não consigo ver a legenda, apenas a legenda do segundo gráfico das curvas. Ao tentar redimensionar a janela do primeiro gráfico para tentar acessar a legenda, a simulação "reinicia" e fica rodando sem parar, e ao tentar fechar a janela, o R trava e fecha automaticamente..

**Comment by adalardo** [comment]
Realmente a janela do gráfico das simulações roda novamente a simulação ao ser redimensionada, vou tentar corrigir isso. Mas não consigo reproduzir o problema da legenda...

**Comment by adalardo** [comment]
Já foi arrumado para a próxima versão do pacote.
