### ISSUE TITLE
Opção area/distance ratio em Island Biogeography

### ISSUE THREAD

**Issue by piklprado** [ecovirt/EcoVirtualPlugin#12]
A turma de Ecologia de comunidades 2016 não entendeu para que serve este botão. Contribuiu para isso que ele aparentemente não faz nada. Eu não lembrei o motivo dessa opção(ou talvez nunca soube ...): não bastaria os 4 coeficientes das relações entre as taxas (I e E) e atributos das ilhas (área e distância)?

**Comment by adalardo** [comment]
Essa razão define o quanto a distancia e a area influencia as taxas de extinção e colonização. Quanto a razao é 1 a extinção só é afetada pela area e a imigração so pela distância. O valor de zero define o inverso. O padrão é que ambas taxas sejam afetadas igualmente pela distância e área. Por algum motivo esse valor não está sendo repassado da interface gráfica, para a função do EcoVirtual. Vou ajustar isso.

**Comment by adalardo** [comment]
implementado para a próxima versão do pacote

**Comment by piklprado** [comment]
Nossa (minha e da turma) é por que este parâmetro é necessário, além dos coeficientes de efeito de área e distância sobre colonização e extinção. Outra questão que surgiur como este parâmetro define o peso relativo de cada uma. Ajudaria se o help tiver a expressão do modelo incluindo este parâmetro.
