### ISSUE TITLE
Demographic Stochasicity

### ISSUE THREAD

**Issue by Del-Bel** [ecovirt/EcoVirtualPlugin#3]
A interface para estocasticidade demográfica trava quando o tempo ou o tamanho inicial é 100 com birth rate 0,2 e death rate 0,1. Talvez haja alguma forma de otimizar o código para que ele possa lidar com valores grandes

**Comment by adalardo** [comment]
O problema aqui é que sua taxa de crescimento populacional de 10% com uma população de incial de 100 vai estourar a população rapidamente. O crescimento exponencial, como vimos em aula, pode gerar números muito grandes em poucas iterações. 
Para não travar, estabelecemos um máximo para o tamanho populacional de 10000 indivíduos. Estará disponivel na proxima versão!
