### ISSUE TITLE
Demographic stochasticity - parâmetro estranho nos gráficos

### ISSUE THREAD

**Issue by RPGraciotti** [ecovirt/EcoVirtualPlugin#4]
Rodando o modelo com os parâmetros:
Maximum time: 50
Number of simulations: 100
Initial size: 100
Birth rate: 0.2
Death rate: menor ou igual a  0.15
O cabeçalho do gráfico fica: Doubling time: mean = a std dev = b
Para qualquer valor de death rate > 0.15, o cabeçalho retorna a extinctions = x/y

**Comment by RPGraciotti** [comment]
UPDATE

Me parece que não é tanto questão do valor, mas a proporção:
0.2/0.15, 0.3/0.25,  0.4/0.35; todos retornam esse parâmetro no gráfico de doubling time mean std dv.

**Comment by adalardo** [comment]
Solucionado. Disponível na próxima versão!
