### ISSUE TITLE
Interface não aceita constantes de colonização maiores que 100 (EcoVirtual>Two Species>Meta competition)

### ISSUE THREAD

**Issue by mljab** [ecovirt/EcoVirtualPlugin#8]
Quando eu rodo o Meta competition com constantes de colonização maiores que 100, a interface não roda o comando e me devolve o erro:
ERROR: Colonization constant must be between 0 and 10
Para constantes de colonização ≤ 100, a interface funciona.
Entretanto, ao rodar a linha de comando no R script com valores maiores que 100, o programa roda.

**Comment by adalardo** [comment]
Isso é uma restrição imposta para a interface do Rcmdr. Estou retirando para que possa acomodar números maiores que 100 (não sei bem para que!).
